version: "3"
services:
  web:
    image: hub.infervision.com/dev/nginx
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"   
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: